### ISSUE TITLE
Satzart 350 (Klauseln) wird nicht erkannt

### ISSUE THREAD

**Issue by apfelbasti** [oboehm/gdv.xport#33]
Die Satzart 350 (Klauseln) wird nicht erkannt. Diese Satzart betrifft alle Sparten. In der XML-Datei ist die Satzart vorhanden.

**Comment by oboehm** [comment]
Habe jetzt einen Testfall in DatenpaketTest hinzugefügt, um den Fehler zu reproduzieren. Damit tritt folgende Exception auf:
```
18:04:19.893 [main] WARN  gdv.xport.util.SatzFactory - Reduced functionality for (unknown or unsupported) Satzart 0350.030:
gdv.xport.util.NotRegisteredException: unregistered Satzart 350
	at gdv.xport.satz.xml.XmlService.getSatzart(XmlService.java:246) ~[classes/:?]
	at gdv.xport.satz.xml.XmlService.getSatzart(XmlService.java:272) ~[classes/:?]
	at gdv.xport.util.SatzFactory.generateSatz(SatzFactory.java:387) ~[classes/:?]
	at gdv.xport.util.SatzFactory.getSatz(SatzFactory.java:357) ~[classes/:?]
	at gdv.xport.util.SatzFactory.useFallback(SatzFactory.java:556) [classes/:?]
	at gdv.xport.util.SatzFactory.generateDatensatz(SatzFactory.java:407) [classes/:?]
	at gdv.xport.util.SatzFactory.getDatensatz(SatzFactory.java:491) [classes/:?]
	at gdv.xport.util.SatzFactory.getDatensatz(SatzFactory.java:456) [classes/:?]
	at gdv.xport.DatenpaketTest.testIssue33(DatenpaketTest.java:537) [test-classes/:?]
        ...
```
Ich vermute mal, dass dieses Fehlerbild dem aus der Fehlerbeschreibung entspricht.

**Comment by oboehm** [comment]
Mit v3.2.1 behoben.
