### ISSUE TITLE
Satzart 0220.010.9: Feld "Ablauf" not found

### ISSUE THREAD

**Issue by oboehm** [oboehm/gdv.xport#39]
Versucht man, Satz 220 (Sparte 10, Wagnisart 9) zu erstellen und anschließend das Feld "Ablauf" zu setzen, so bekommt man

    java.lang.IllegalArgumentException: Feld "Ablauf" not found
	    at gdv.xport.satz.Satz.set(Satz.java:295)
	    at gdv.xport.satz.Satz.set(Satz.java:307)
	    at gdv.xport.satz.model.Satz220Test.testSetWagnis9Ablauf(Satz220Test.java:245)

als Fehlermeldung.

Hier die Test-Methode, um den Fehler zu reproduzieren (Dank an Wissam Sorkan für den Code):

```java
    @Test
    public void testSetWagnis9Ablauf() {
        Satz220 satz220 = new Satz220(10);
        satz220.set(Feld220Wagnis9.ABLAUF, "02022020");
    }
```

**Comment by oboehm** [comment]
mit 4.0.4 behoben (s. [Release Notes](https://github.com/oboehm/gdv.xport/blob/master/doc/release-notes.adoc))
