### ISSUE TITLE
Version 6.2.0 nicht kompatibel mit Java 8

### ISSUE THREAD

**Issue by Klausus01** [oboehm/gdv.xport#84]
Hi Oli,

wir entwickeln gegen Java 8.
Beim Versuch, die aktuelle Rel-Version zu benutzen, erhalten wir folgende Fehlermeldung:

Exception in thread "main" java.lang.UnsupportedClassVersionError: patterntesting/runtime/log/LogWatch has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at gdv.xport.satz.xml.XmlService.parse(XmlService.java:210)
at gdv.xport.satz.xml.XmlService.<init>(XmlService.java:206)
at gdv.xport.satz.xml.XmlService.<init>(XmlService.java:190)
at gdv.xport.satz.xml.XmlService.createXmlService(XmlService.java:160)
at gdv.xport.satz.xml.XmlService.createXmlService(XmlService.java:153)
at gdv.xport.satz.xml.XmlService.getInstance(XmlService.java:95)

Kannst du hier bitte neu kompatibel bauen?

Gruß
Klaus

**Comment by oboehm** [comment]
Hallo Klaus,

wird schwierig. Bin gerade im Tessin im Urlaub. Problem ist, dass ich eine Reihe von Libs aktualisiert habe, u.a. auch die von patterntesting-rt. Aber was du probieren kannst: Exclude einfach die Patterntesting-Lib aus den Dependencies und füge dann explizit die patterntesting-rt 2.1.2 (das müsste die letzte Version sein, die mit Java 8 gebaut wurde. Im POM müsste dass dann etwas so aussehen:

<dependency>
  <groupId>com.github.oboehm</groupId>
  <artifactId>gdv-xport-lib</artifactId>
  <version>6.2.0</version>
<exclusions>
  <exclusion>
    <groupId>org.patterntesting</groupId>
    <artifactId>patterntesting-rt</artifactId>
  </exclusion>
</exclusions>
</dependency>
<dependency>
  <groupId>org.patterntesting</groupId>
  <artifactId>patterntesting-rt</artifactId>
  <version>2.1.2</version>
</dependency>


Mit freundlichen Grüßen
oli b.

**Comment by oboehm** [comment]
mit 6.2.1 behoben
